config = {
    
    ['recoils'] = {

        ['ak'] = 13,
        ['m4'] = 12,
        ['g36c'] = 15,
        ['imbel'] = 30,
        ['magnum'] = 30,
        ['revolver'] = 30,
        ['five'] = 8,
        ['glock'] = 9,
        ['escopeta'] = 150,
        ['mp5'] = 14,
        ['thompson'] = 14,
        ['tec9'] = 14,
        ['p90'] = 14,
        ['skorpion'] = 20,
        ['machine1'] = 35,
        ['uzi'] = 20,
        ['bazooka'] = 300,
        ['m240'] = 180,
        ['kar98'] = 220,

    },

    armas = {
        
        ['bazooka'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'Leon_ATM-4_D', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'ds2'},

            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'Leon_ATM-4_D', nameSkin = 'flamengo'},
        },

        ['faca2'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'wp01_006_albmout', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'wp01_006_albmout', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'wp01_006_albmout', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'wp01_006_albmout', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'wp01_006_albmout', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'wp01_006_albmout', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'wp01_006_albmout', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'wp01_006_albmout', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'wp01_006_albmout', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'wp01_006_albmout', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'wp01_006_albmout', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'wp01_006_albmout', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'wp01_006_albmout', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'wp01_006_albmout', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'wp01_006_albmout', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'wp01_006_albmout', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'wp01_006_albmout', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'wp01_006_albmout', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'wp01_006_albmout', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'wp01_006_albmout', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'wp01_006_albmout', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'wp01_006_albmout', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'wp01_006_albmout', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'wp01_006_albmout', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'wp01_006_albmout', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'wp01_006_albmout', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'wp01_006_albmout', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'wp01_006_albmout', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'wp01_006_albmout', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'wp01_006_albmout', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'wp01_006_albmout', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'wp01_006_albmout', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'wp01_006_albmout', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'wp01_006_albmout', nameSkin = 'flamengo'},
        },

        ['jhammer'] = {
            ['camuflada'] = {       weaponName = 'jhammer2', nameSkin = 'camuflada'},
            ['natal'] = {           weaponName = 'jhammer2', nameSkin = 'natal'},
            ['barbie'] = {          weaponName = 'jhammer2', nameSkin = 'barbie'},
            ['snow'] = {            weaponName = 'jhammer2', nameSkin = 'snow'},
            ['padrao'] = {          weaponName = 'jhammer2', nameSkin = 'padrao'},
            ['n21'] = {             weaponName = 'jhammer2', nameSkin = 'n21'},
            ['danger'] = {          weaponName = 'jhammer2', nameSkin = 'danger'},
            ['luiviton'] = {        weaponName = 'jhammer2', nameSkin = 'luiviton'},
            ['raiopurple'] = {      weaponName = 'jhammer2', nameSkin = 'raiopurple'},
            ['zebra'] = {           weaponName = 'jhammer2', nameSkin = 'zebra'},
            ['jaguar'] = {          weaponName = 'jhammer2', nameSkin = 'jaguar'},
            ['postit'] = {          weaponName = 'jhammer2', nameSkin = 'postit'},
            ['stars'] = {           weaponName = 'jhammer2', nameSkin = 'stars'},
            ['nebulared'] = {       weaponName = 'jhammer2', nameSkin = 'nebulared'},
            ['nebulablue'] = {      weaponName = 'jhammer2', nameSkin = 'nebulablue'},
            ['fire'] = {            weaponName = 'jhammer2', nameSkin = 'fire'},
            ['dollarsign'] = {      weaponName = 'jhammer2', nameSkin = 'dollarsign'},
            ['colorful'] = {        weaponName = 'jhammer2', nameSkin = 'colorful'},
            ['butterflies'] = {     weaponName = 'jhammer2', nameSkin = 'butterflies'},
            ['raiored'] = {         weaponName = 'jhammer2', nameSkin = 'raiored'},
            ['raioverde'] = {       weaponName = 'jhammer2', nameSkin = 'raioverde'},
            ['camupink'] = {        weaponName = 'jhammer2', nameSkin = 'camupink'},
            ['camured'] = {         weaponName = 'jhammer2', nameSkin = 'camured'},
            ['graficsgreen'] = {    weaponName = 'jhammer2', nameSkin = 'graficsgreen'},
            ['graficsred'] = {      weaponName = 'jhammer2', nameSkin = 'graficsred'},
            ['onca'] = {            weaponName = 'jhammer2', nameSkin = 'onca'},
            ['tones'] = {           weaponName = 'jhammer2', nameSkin = 'tones'},
            ['os1'] = {             weaponName = 'jhammer2', nameSkin = 'os1'},
            ['ps1'] = {             weaponName = 'jhammer2', nameSkin = 'ps1'},
            ['ds1'] = {             weaponName = 'jhammer2', nameSkin = 'ds1'},
            ['os2'] = {             weaponName = 'jhammer2', nameSkin = 'os2'},
            ['ps2'] = {             weaponName = 'jhammer2', nameSkin = 'ps2'},
            ['ds2'] = {             weaponName = 'jhammer2', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'jhammer2', nameSkin = 'flamengo'},
            
        },

        ['motoserra'] = {
            ['camuflada'] = {       weaponName = 'motoserra', nameSkin = 'camuflada'},
            ['natal'] = {           weaponName = 'motoserra', nameSkin = 'natal'},
            ['barbie'] = {          weaponName = 'motoserra', nameSkin = 'barbie'},
            ['snow'] = {            weaponName = 'motoserra', nameSkin = 'snow'},
            ['padrao'] = {          weaponName = 'motoserra', nameSkin = 'padrao'},
            ['n21'] = {             weaponName = 'motoserra', nameSkin = 'n21'},
            ['danger'] = {          weaponName = 'motoserra', nameSkin = 'danger'},
            ['luiviton'] = {        weaponName = 'motoserra', nameSkin = 'luiviton'},
            ['raiopurple'] = {      weaponName = 'motoserra', nameSkin = 'raiopurple'},
            ['zebra'] = {           weaponName = 'motoserra', nameSkin = 'zebra'},
            ['jaguar'] = {          weaponName = 'motoserra', nameSkin = 'jaguar'},
            ['postit'] = {          weaponName = 'motoserra', nameSkin = 'postit'},
            ['stars'] = {           weaponName = 'motoserra', nameSkin = 'stars'},
            ['nebulared'] = {       weaponName = 'motoserra', nameSkin = 'nebulared'},
            ['nebulablue'] = {      weaponName = 'motoserra', nameSkin = 'nebulablue'},
            ['fire'] = {            weaponName = 'motoserra', nameSkin = 'fire'},
            ['dollarsign'] = {      weaponName = 'motoserra', nameSkin = 'dollarsign'},
            ['colorful'] = {        weaponName = 'motoserra', nameSkin = 'colorful'},
            ['butterflies'] = {     weaponName = 'motoserra', nameSkin = 'butterflies'},
            ['raiored'] = {         weaponName = 'motoserra', nameSkin = 'raiored'},
            ['raioverde'] = {       weaponName = 'motoserra', nameSkin = 'raioverde'},
            ['camupink'] = {        weaponName = 'motoserra', nameSkin = 'camupink'},
            ['camured'] = {         weaponName = 'motoserra', nameSkin = 'camured'},
            ['graficsgreen'] = {    weaponName = 'motoserra', nameSkin = 'graficsgreen'},
            ['graficsred'] = {      weaponName = 'motoserra', nameSkin = 'graficsred'},
            ['onca'] = {            weaponName = 'motoserra', nameSkin = 'onca'},
            ['tones'] = {           weaponName = 'motoserra', nameSkin = 'tones'},
            ['os1'] = {             weaponName = 'motoserra', nameSkin = 'os1'},
            ['ps1'] = {             weaponName = 'motoserra', nameSkin = 'ps1'},
            ['ds1'] = {             weaponName = 'motoserra', nameSkin = 'ds1'},
            ['os2'] = {             weaponName = 'motoserra', nameSkin = 'os2'},
            ['ps2'] = {             weaponName = 'motoserra', nameSkin = 'ps2'},
            ['ds2'] = {             weaponName = 'motoserra', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'motoserra', nameSkin = 'flamengo'},
            
        },

        ['faca3'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'karambit', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'karambit', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'karambit', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'karambit', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'karambit', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'karambit', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'karambit', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'karambit', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'karambit', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'karambit', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'karambit', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'karambit', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'karambit', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'karambit', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'karambit', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'karambit', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'karambit', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'karambit', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'karambit', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'karambit', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'karambit', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'karambit', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'karambit', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'karambit', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'karambit', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'karambit', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'karambit', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'karambit', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'karambit', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'karambit', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'karambit', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'karambit', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'karambit', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'karambit', nameSkin = 'flamengo'},
            
        },

        ['caseira'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'wpn', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'wpn', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'wpn', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'wpn', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'wpn', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'wpn', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'wpn', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'wpn', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'wpn', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'wpn', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'wpn', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'wpn', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'wpn', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'wpn', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'wpn', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'wpn', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'wpn', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'wpn', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'wpn', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'wpn', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'wpn', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'wpn', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'wpn', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'wpn', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'wpn', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'wpn', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'wpn', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'wpn', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'wpn', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'wpn', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'wpn', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'wpn', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'wpn', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'wpn', nameSkin = 'flamengo'},
            
        },
        
        ['escopeta'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = {weaponName = 'remmy', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'remmy', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'remmy', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'remmy', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'remmy', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'remmy', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'remmy', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'remmy', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'remmy', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'remmy', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'remmy', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'remmy', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'remmy', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'remmy', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'remmy', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'remmy', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'remmy', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'remmy', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'remmy', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'remmy', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'remmy', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'remmy', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'remmy', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'remmy', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'remmy', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'remmy', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'remmy', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'remmy', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'remmy', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'remmy', nameSkin = 'ds1'},
            ['ps2'] = {weaponName = 'remmy', nameSkin = 'ps2'},
            ['os2'] = {weaponName = 'remmy', nameSkin = 'os2'},
            ['ds2'] = {weaponName = 'remmy', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'remmy', nameSkin = 'flamengo'},
        },
        
        ['magnum'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'Tex_0010', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'Tex_0010', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'Tex_0010', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'Tex_0010', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'Tex_0010', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'Tex_0010', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'Tex_0010', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'Tex_0010', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'Tex_0010', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'Tex_0010', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'Tex_0010', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'Tex_0010', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'Tex_0010', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'Tex_0010', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'Tex_0010', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'Tex_0010', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'Tex_0010', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'Tex_0010', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'Tex_0010', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'Tex_0010', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'Tex_0010', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'Tex_0010', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'Tex_0010', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'Tex_0010', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'Tex_0010', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'Tex_0010', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'Tex_0010', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'Tex_0010', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'Tex_0010', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'Tex_0010', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'Tex_0010', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'Tex_0010', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'Tex_0010', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'Tex_0010', nameSkin = 'flamengo'},
        },
        
        ['m240'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'boxmag', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'boxmag', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'boxmag', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'boxmag', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'boxmag', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'boxmag', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'boxmag', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'boxmag', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'boxmag', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'boxmag', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'boxmag', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'boxmag', nameSkin = 'postit'},
            ['nebulared'] = {weaponName = 'boxmag', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'boxmag', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'boxmag', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'boxmag', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'boxmag', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'boxmag', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'boxmag', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'boxmag', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'boxmag', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'boxmag', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'boxmag', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'boxmag', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'boxmag', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'boxmag', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'boxmag', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'boxmag', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'boxmag', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'boxmag', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'boxmag', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'boxmag', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'boxmag', nameSkin = 'flamengo'},
        },

        ['imbel'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'Made by LTUGA', nameSkin = 'camuflada'},
            ['barbie'] = {weaponName = 'Made by LTUGA', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'Made by LTUGA', nameSkin = 'natal'},
            ['snow'] = {weaponName = 'Made by LTUGA', nameSkin = 'snow'},
            ['redline'] = {imagem = 'redline.png', weaponName = 'Made by LTUGA', nameSkin = 'redline'},
            ['ultra'] = {imagem = 'ultra.png', weaponName = 'Made by LTUGA', nameSkin = 'ultra'},
            ['reddragon'] = {imagem = 'reddragon.png', weaponName = 'Made by LTUGA', nameSkin = 'reddragon'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'Made by LTUGA', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'Made by LTUGA', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'Made by LTUGA', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'Made by LTUGA', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'Made by LTUGA', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'Made by LTUGA', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'Made by LTUGA', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'Made by LTUGA', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'Made by LTUGA', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'Made by LTUGA', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'Made by LTUGA', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'Made by LTUGA', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'Made by LTUGA', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'Made by LTUGA', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'Made by LTUGA', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'Made by LTUGA', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'Made by LTUGA', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'Made by LTUGA', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'Made by LTUGA', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'Made by LTUGA', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'Made by LTUGA', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'Made by LTUGA', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'Made by LTUGA', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'Made by LTUGA', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'Made by LTUGA', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'Made by LTUGA', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'Made by LTUGA', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'Made by LTUGA', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'Made by LTUGA', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'Made by LTUGA', nameSkin = 'flamengo'},
        },
        
        ['mp5'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'mp5a5', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'mp5a5', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'mp5a5', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'mp5a5', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'mp5a5', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'mp5a5', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'mp5a5', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'mp5a5', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'mp5a5', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'mp5a5', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'mp5a5', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'mp5a5', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'mp5a5', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'mp5a5', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'mp5a5', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'mp5a5', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'mp5a5', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'mp5a5', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'mp5a5', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'mp5a5', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'mp5a5', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'mp5a5', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'mp5a5', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'mp5a5', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'mp5a5', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'mp5a5', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'mp5a5', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'mp5a5', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'mp5a5', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'mp5a5', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'mp5a5', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'mp5a5', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'mp5a5', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'mp5a5', nameSkin = 'flamengo'},
            
        },
        
        ['faca'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'faca', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'faca', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'faca', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'faca', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'faca', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'faca', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'faca', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'faca', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'faca', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'faca', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'faca', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'faca', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'faca', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'faca', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'faca', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'faca', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'faca', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'faca', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'faca', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'faca', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'faca', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'faca', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'faca', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'faca', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'faca', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'faca', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'faca', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'faca', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'faca', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'faca', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'faca', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'faca', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'faca', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'faca', nameSkin = 'flamengo'},
            
        },
        
        ['uzi'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'uzi', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'uzi', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'uzi', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'uzi', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'uzi', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'uzi', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'uzi', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'uzi', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'uzi', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'uzi', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'uzi', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'uzi', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'uzi', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'uzi', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'uzi', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'uzi', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'uzi', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'uzi', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'uzi', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'uzi', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'uzi', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'uzi', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'uzi', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'uzi', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'uzi', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'uzi', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'uzi', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'uzi', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'uzi', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'uzi', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'uzi', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'uzi', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'uzi', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'uzi', nameSkin = 'flamengo'},
            
        },
        
        ['thompson'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'tec_9b', nameSkin = 'camuflada'},
            ['snow'] = {weaponName = 'tec_9b', nameSkin = 'snow'},
            ['barbie'] = {weaponName = 'tec_9b', nameSkin = 'barbie'},
            ['natal'] = {weaponName = 'tec_9b', nameSkin = 'natal'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'tec_9b', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'tec_9b', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'tec_9b', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'tec_9b', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'tec_9b', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'tec_9b', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'tec_9b', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'tec_9b', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'tec_9b', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'tec_9b', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'tec_9b', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'tec_9b', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'tec_9b', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'tec_9b', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'tec_9b', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'tec_9b', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'tec_9b', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'tec_9b', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'tec_9b', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'tec_9b', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'tec_9b', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'tec_9b', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'tec_9b', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'tec_9b', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'tec_9b', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'tec_9b', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'tec_9b', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'tec_9b', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'tec_9b', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'tec_9b', nameSkin = 'flamengo'},
            
        },
        
        ['five'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'fiveseven_D', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'fiveseven_D', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'fiveseven_D', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'fiveseven_D', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'fiveseven_D', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'fiveseven_D', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'fiveseven_D', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'fiveseven_D', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'fiveseven_D', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'fiveseven_D', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'fiveseven_D', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'fiveseven_D', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'fiveseven_D', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'fiveseven_D', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'fiveseven_D', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'fiveseven_D', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'fiveseven_D', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'fiveseven_D', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'fiveseven_D', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'fiveseven_D', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'fiveseven_D', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'fiveseven_D', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'fiveseven_D', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'fiveseven_D', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'fiveseven_D', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'fiveseven_D', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'fiveseven_D', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            
            ['os1'] = {weaponName = 'fiveseven_D', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'fiveseven_D', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'fiveseven_D', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'fiveseven_D', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'fiveseven_D', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'fiveseven_D', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'fiveseven_D', nameSkin = 'flamengo'},
            
        },

        ['machine1'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'Machine_Pistol', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'Machine_Pistol', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'Machine_Pistol', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'Machine_Pistol', nameSkin = 'snow'},

            ['golds'] = {weaponName = 'Machine_Pistol', nameSkin = 'golds'},
            ['green'] = {weaponName = 'Machine_Pistol', nameSkin = 'green'},
            ['pink'] = {weaponName = 'Machine_Pistol', nameSkin = 'pink'},
            ['orange'] = {weaponName = 'Machine_Pistol', nameSkin = 'orange'},
            ['platinum'] = {weaponName = 'Machine_Pistol', nameSkin = 'platinum'},
            ['lspd'] = {weaponName = 'Machine_Pistol', nameSkin = 'lspd'},
            ['army'] = {weaponName = 'Machine_Pistol', nameSkin = 'army'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'Machine_Pistol', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'Machine_Pistol', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'Machine_Pistol', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'Machine_Pistol', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'Machine_Pistol', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'Machine_Pistol', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'Machine_Pistol', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'Machine_Pistol', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'Machine_Pistol', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'Machine_Pistol', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'Machine_Pistol', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'Machine_Pistol', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'Machine_Pistol', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'Machine_Pistol', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'Machine_Pistol', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'Machine_Pistol', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'Machine_Pistol', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'Machine_Pistol', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'Machine_Pistol', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'Machine_Pistol', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'Machine_Pistol', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'Machine_Pistol', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'Machine_Pistol', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'Machine_Pistol', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'Machine_Pistol', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'Machine_Pistol', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'Machine_Pistol', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'Machine_Pistol', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'Machine_Pistol', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'Machine_Pistol', nameSkin = 'flamengo'},
            
        },

        ['machine2'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'Machine_Pistol', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'Machine_Pistol', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'Machine_Pistol', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'Machine_Pistol', nameSkin = 'snow'},

            ['golds'] = {weaponName = 'Machine_Pistol', nameSkin = 'golds'},
            ['green'] = {weaponName = 'Machine_Pistol', nameSkin = 'green'},
            ['pink'] = {weaponName = 'Machine_Pistol', nameSkin = 'pink'},
            ['orange'] = {weaponName = 'Machine_Pistol', nameSkin = 'orange'},
            ['platinum'] = {weaponName = 'Machine_Pistol', nameSkin = 'platinum'},
            ['lspd'] = {weaponName = 'Machine_Pistol', nameSkin = 'lspd'},
            ['army'] = {weaponName = 'Machine_Pistol', nameSkin = 'army'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'Machine_Pistol', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'Machine_Pistol', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'Machine_Pistol', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'Machine_Pistol', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'Machine_Pistol', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'Machine_Pistol', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'Machine_Pistol', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'Machine_Pistol', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'Machine_Pistol', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'Machine_Pistol', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'Machine_Pistol', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'Machine_Pistol', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'Machine_Pistol', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'Machine_Pistol', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'Machine_Pistol', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'Machine_Pistol', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'Machine_Pistol', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'Machine_Pistol', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'Machine_Pistol', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'Machine_Pistol', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'Machine_Pistol', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'Machine_Pistol', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'Machine_Pistol', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            ['os1'] = {weaponName = 'Machine_Pistol', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'Machine_Pistol', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'Machine_Pistol', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'Machine_Pistol', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'Machine_Pistol', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'Machine_Pistol', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'Machine_Pistol', nameSkin = 'flamengo'},
        },

        ['vector'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'KrissSV_D', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'KrissSV_D', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'KrissSV_D', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'KrissSV_D', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'KrissSV_D', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'KrissSV_D', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'KrissSV_D', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'KrissSV_D', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'KrissSV_D', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'KrissSV_D', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'KrissSV_D', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'KrissSV_D', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'KrissSV_D', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'KrissSV_D', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'KrissSV_D', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'KrissSV_D', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'KrissSV_D', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'KrissSV_D', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'KrissSV_D', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'KrissSV_D', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'KrissSV_D', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'KrissSV_D', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'KrissSV_D', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'KrissSV_D', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'KrissSV_D', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'KrissSV_D', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'KrissSV_D', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            
            ['os1'] = {weaponName = 'KrissSV_D', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'KrissSV_D', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'KrissSV_D', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'KrissSV_D', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'KrissSV_D', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'KrissSV_D', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'KrissSV_D', nameSkin = 'flamengo'},
            
        },

        ['p90'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'body', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'body', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'body', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'body', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'body', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'body', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'body', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'body', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'body', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'body', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'body', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'body', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'body', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'body', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'body', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'body', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'body', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'body', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'body', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'body', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'body', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'body', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'body', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'body', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'body', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'body', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'body', nameSkin = 'tones'},
            -- === [ VIPS ] === --
            
            ['os1'] = {weaponName = 'body', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'body', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'body', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'body', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'body', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'body', nameSkin = 'ds2'},
            -- === [ TIMES ] === --
            ['flamengo'] = {weaponName = 'body', nameSkin = 'flamengo'},
            
        },

        ['taco'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'billy', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'billy', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'billy', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'billy', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'billy', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'billy', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'billy', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'billy', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'billy', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'billy', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'billy', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'billy', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'billy', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'billy', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'billy', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'billy', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'billy', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'billy', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'billy', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'billy', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'billy', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'billy', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'billy', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'billy', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'billy', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'billy', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'billy', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'billy', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'billy', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'billy', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'billy', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'billy', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'billy', nameSkin = 'ds2'},
            
        },

        ['taco2'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'gunpoolcue', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'gunpoolcue', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'gunpoolcue', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'gunpoolcue', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'gunpoolcue', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'gunpoolcue', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'gunpoolcue', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'gunpoolcue', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'gunpoolcue', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'gunpoolcue', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'gunpoolcue', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'gunpoolcue', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'gunpoolcue', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'gunpoolcue', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'gunpoolcue', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'gunpoolcue', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'gunpoolcue', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'gunpoolcue', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'gunpoolcue', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'gunpoolcue', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'gunpoolcue', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'gunpoolcue', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'gunpoolcue', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'gunpoolcue', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'gunpoolcue', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'gunpoolcue', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'gunpoolcue', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'gunpoolcue', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'gunpoolcue', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'gunpoolcue', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'gunpoolcue', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'gunpoolcue', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'gunpoolcue', nameSkin = 'ds2'},
            
        },

        ['taco3'] = {
            -- === [ NORMAL 1 ] === --
            ['camuflada'] = { weaponName = 'gunpoolcue', nameSkin = 'camuflada'},
            ['natal'] = {weaponName = 'gunpoolcue', nameSkin = 'natal'},
            ['barbie'] = {weaponName = 'gunpoolcue', nameSkin = 'barbie'},
            ['snow'] = {weaponName = 'gunpoolcue', nameSkin = 'snow'},
            -- === [ NORMAL 2 ] === --
            ['padrao'] = {weaponName = 'gunpoolcue', nameSkin = 'padrao'},
            ['n21'] = {weaponName = 'gunpoolcue', nameSkin = 'n21'},
            ['danger'] = {weaponName = 'gunpoolcue', nameSkin = 'danger'},
            ['luiviton'] = {weaponName = 'gunpoolcue', nameSkin = 'luiviton'},
            ['raiopurple'] = {weaponName = 'gunpoolcue', nameSkin = 'raiopurple'},
            ['zebra'] = {weaponName = 'gunpoolcue', nameSkin = 'zebra'},
            ['jaguar'] = {weaponName = 'gunpoolcue', nameSkin = 'jaguar'},
            ['postit'] = {weaponName = 'gunpoolcue', nameSkin = 'postit'},
            ['stars'] = {weaponName = 'gunpoolcue', nameSkin = 'stars'},
            ['nebulared'] = {weaponName = 'gunpoolcue', nameSkin = 'nebulared'},
            ['nebulablue'] = {weaponName = 'gunpoolcue', nameSkin = 'nebulablue'},
            ['fire'] = {weaponName = 'gunpoolcue', nameSkin = 'fire'},
            ['dollarsign'] = {weaponName = 'gunpoolcue', nameSkin = 'dollarsign'},
            ['colorful'] = {weaponName = 'gunpoolcue', nameSkin = 'colorful'},
            ['butterflies'] = {weaponName = 'gunpoolcue', nameSkin = 'butterflies'},
            ['raiored'] = {weaponName = 'gunpoolcue', nameSkin = 'raiored'},
            ['raioverde'] = {weaponName = 'gunpoolcue', nameSkin = 'raioverde'},
            ['camupink'] = {weaponName = 'gunpoolcue', nameSkin = 'camupink'},
            ['camured'] = {weaponName = 'gunpoolcue', nameSkin = 'camured'},
            ['graficsgreen'] = {weaponName = 'gunpoolcue', nameSkin = 'graficsgreen'},
            ['graficsred'] = {weaponName = 'gunpoolcue', nameSkin = 'graficsred'},
            ['onca'] = {weaponName = 'gunpoolcue', nameSkin = 'onca'},
            ['tones'] = {weaponName = 'gunpoolcue', nameSkin = 'tones'},
            -- === [ VIPS 1 ] === --
            ['os1'] = {weaponName = 'gunpoolcue', nameSkin = 'os1'},
            ['ps1'] = {weaponName = 'gunpoolcue', nameSkin = 'ps1'},
            ['ds1'] = {weaponName = 'gunpoolcue', nameSkin = 'ds1'},
            ['os2'] = {weaponName = 'gunpoolcue', nameSkin = 'os2'},
            ['ps2'] = {weaponName = 'gunpoolcue', nameSkin = 'ps2'},
            ['ds2'] = {weaponName = 'gunpoolcue', nameSkin = 'ds2'},
            
        },

    },
    notifyS = function (player, message, type)
        triggerClientEvent(player, "ve.notify", player, "Adesivo", type, message, 5)
    end
}